version: "3.5"

x-hong-kong:
  projectRoutes:
    - route: "/"
      forwardHost: "http://rj-site"
      domain: "10.8.102.203:9900"
    - route: "/cms"
      forwardHost: "http://ghost:2368"
      domain: "10.8.102.203:9900"

services:
  rj-site:
    restart: always
    build:
      context: ./front-end
      dockerfile: dev.dockerfile
    env_file:
      - dev.env
    ports:
      - 9910:80
    networks:
      - rjnet
    volumes:
      - ./front-end/pages:/app/pages
      - ./front-end/public:/app/public
      - ./front-end/components:/app/components
      - ./front-end/typings:/app/typings
      - ./front-end/util:/app/util

  rj-site-back-end:
    restart: always
    build:
      context: ./back-end
      dockerfile: dev.dockerfile
    env_file:
      - dev.env
    ports:
      - 9912:80
    networks:
      - rjnet
    volumes:
      - ./back-end/main:/app/main
      - ./back-end/vendor:/app/vendor

  ghost:
    image: ghost:latest
    restart: always
    ports:
      - 9911:2368
    environment:
      url: http://localhost:9900/cms/
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: root
      database__connection__password: MyStrongPassword
      database__connection__database: ghost
    volumes:
      - ./content:/var/lib/ghost/content
    networks:
      - rjnet

networks:
  rjnet:
    name: RJnet
