version: "3.5"

x-hong-kong:
  projectRoutes:
    - route: "/"
      forwardHost: "http://rj-site"
      domain: "10.8.102.203:9900"
    - route: "/cms"
      forwardHost: "http://ghost:2368"
      domain: "10.8.102.203:9900"

services:
  rj-site:
    restart: always
    build: .
    env_file:
      - dev.env
    ports:
      - 9910:80
    networks:
      - rjnet
  ghost-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyStrongPassword
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - rjnet
  ghost:
    image: ghost:latest
    restart: always
    ports:
      - 9911:2368
    depends_on:
      - ghost-db
    environment:
      url: http://localhost:9900/cms/
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: root
      database__connection__password: MyStrongPassword
      database__connection__database: ghost
    volumes:
      - ./content:/var/lib/ghost/content
    networks:
      - rjnet

networks:
  rjnet:
    name: RJnet
