version: "3.5"

x-hong-kong:
  buildInfo:
    - dockerfile: "front-end/dockerfile"
      name: "rj-site"
      context: "front-end"
    - dockerfile: "back-end/dockerfile"
      name: "rj-site-back-end"
      context: "back-end"
  projectRoutes:
    - route: "/"
      forwardHost: "http://rj-site"
    - route: "/api"
      forwardHost: "http://rj-site-back-end"
    - route: "/cms"
      forwardHost: "http://ghost:2368"

services:
  rj-site:
    image: therileyjohnson/rj-site-novel_rj-site:latest
    restart: always
    env_file:
      - prod.env
    networks:
      - rjnet
  rj-site-back-end:
    image: therileyjohnson/rj-site-novel_rj-site-back-end:latest
    restart: always
    env_file:
      - prod.env
    networks:
      - rjnet
  ghost:
    image: ghost:latest
    restart: always
    depends_on:
      - ghost-db
    environment:
      url: https://therileyjohnson.com/cms/
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: root
      database__connection__password: MyStrongPassword
      database__connection__database: ghost
    volumes:
      - ./content:/var/lib/ghost/content
    networks:
      - rjnet
  ghost-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyStrongPassword
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - rjnet

networks:
  rjnet:
    name: RJnet
